#!/usr/bin/perl -w 

use EV;
use AnyEvent;
use Mojolicious::Lite;
use Data::Dumper;
use JSON;
use Database;

app->attr( db => sub { Database->new });

get '/' => sub {
    my $self = shift;
    my $db = $self->app->db;

    $db->sleep(sub {
        $self->render(text => 'Done'); 
    });
};

my @resources = qw(session event alert);
for my $resource (@resources) {
    get "/$resource" => sub { shift->render(text => 'Nothing to see here.') };
}

my $clients = [];
websocket '/echo' => sub {
    my $self = shift;

    $self->app->log->debug("Websocket connected.");

    push @$clients, $self->tx;
    $self->on(message => sub {
        my ($self, $message) = @_;

        for my $client (@$clients) {
            $client->send_message(encode_json({ 
                status => "Got " .scalar @$clients. " clients!",
            }));
        }
    });

    $self->on(finish => sub {
        my $self = shift;
        $self->app->log->debug("Websocket disconnected.");
    });
};

app->start;

